/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphdrawer;

import edu.uci.ics.jung.visualization.VisualizationImageServer;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class GraphShower extends javax.swing.JFrame {
    int number;
    ArrayList<Pair> edges2;
    GraphImage graphImage;
    /**
     * Creates new form GraphShower
     */
    public GraphShower() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numberText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edgesArea = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        graph = new javax.swing.JPanel();
        graphScroller = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        graphInfo = new javax.swing.JTextArea();
        adjacencyListButton = new javax.swing.JButton();
        adjacencyMatrixButton = new javax.swing.JButton();
        incidenceMatrixButton = new javax.swing.JButton();
        representationMatrixButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph Drawer");

        jLabel1.setText("Number of vertices :");

        numberText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel3.setText("Edges :");

        edgesArea.setColumns(20);
        edgesArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        edgesArea.setRows(5);
        jScrollPane2.setViewportView(edgesArea);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputsLayout = new javax.swing.GroupLayout(inputs);
        inputs.setLayout(inputsLayout);
        inputsLayout.setHorizontalGroup(
            inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputsLayout.createSequentialGroup()
                .addGroup(inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inputsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        inputsLayout.setVerticalGroup(
            inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout graphLayout = new javax.swing.GroupLayout(graph);
        graph.setLayout(graphLayout);
        graphLayout.setHorizontalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(graphScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        graphLayout.setVerticalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphScroller, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        graphInfo.setColumns(20);
        graphInfo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        graphInfo.setRows(5);
        jScrollPane3.setViewportView(graphInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        adjacencyListButton.setText("AdjacencyList");
        adjacencyListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjacencyListButtonActionPerformed(evt);
            }
        });

        adjacencyMatrixButton.setText("Adjacency Matrix");
        adjacencyMatrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjacencyMatrixButtonActionPerformed(evt);
            }
        });

        incidenceMatrixButton.setText("Incidence Matrix");
        incidenceMatrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incidenceMatrixButtonActionPerformed(evt);
            }
        });

        representationMatrixButton.setText("Representation Matrix");
        representationMatrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                representationMatrixButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(adjacencyListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(adjacencyMatrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(incidenceMatrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(representationMatrixButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adjacencyListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adjacencyMatrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incidenceMatrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(representationMatrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if( !edgesArea.getText().isEmpty() && !numberText.getText().isEmpty()){
            number = Integer.parseInt(numberText.getText());
            String []edges = edgesArea.getText().split("\n");
            edges2 =new ArrayList<Pair>();
            for(int i=0 ; i < edges.length;++i){
                String [] eachEdge = edges[i].split(" ");
                Pair pair = new Pair(eachEdge[0],eachEdge[1]);
                edges2.add(pair);
            }
            graphImage = new GraphImage(number,edges2);
            VisualizationImageServer vs = graphImage.getGraphImageServer();
            graphScroller.add(vs);
        }
        else{
            JOptionPane.showMessageDialog(null, "fill all fields");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void representationMatrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_representationMatrixButtonActionPerformed
        // TODO add your handling code here:
        RepresentationMatrix adj = new RepresentationMatrix(number);
        for(int i=0 ; i<edges2.size() ; i++){
            adj.addEdge(Integer.parseInt(edges2.get(i).getKey()),Integer.parseInt(edges2.get(i).getValue()) );
        }
        graphInfo.setText(adj.toString());
    }//GEN-LAST:event_representationMatrixButtonActionPerformed

    private void adjacencyListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjacencyListButtonActionPerformed
        // TODO add your handling code here:
        AdjacencyList adj = new AdjacencyList(number);
        for(int i=0 ; i<edges2.size() ; i++){
            adj.addEdge(Integer.parseInt(edges2.get(i).getKey()),Integer.parseInt(edges2.get(i).getValue()) );
        }
        graphInfo.setText(adj.getFormattedList());
    }//GEN-LAST:event_adjacencyListButtonActionPerformed

    private void adjacencyMatrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjacencyMatrixButtonActionPerformed
        // TODO add your handling code here:
        AdjacencyMatrix adj = new AdjacencyMatrix(number);
        for(int i=0 ; i<edges2.size() ; i++){
            adj.addEdge(Integer.parseInt(edges2.get(i).getKey()),Integer.parseInt(edges2.get(i).getValue()) );
        }
        graphInfo.setText(adj.toString());
    }//GEN-LAST:event_adjacencyMatrixButtonActionPerformed

    private void incidenceMatrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidenceMatrixButtonActionPerformed
        // TODO add your handling code here:
        graphInfo.setText(graphImage.getIncMatric());
    }//GEN-LAST:event_incidenceMatrixButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphShower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphShower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphShower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphShower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphShower().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adjacencyListButton;
    private javax.swing.JButton adjacencyMatrixButton;
    private javax.swing.JTextArea edgesArea;
    private javax.swing.JPanel graph;
    private javax.swing.JTextArea graphInfo;
    private javax.swing.JScrollPane graphScroller;
    private javax.swing.JButton incidenceMatrixButton;
    private javax.swing.JPanel inputs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField numberText;
    private javax.swing.JButton representationMatrixButton;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
